#!/usr/bin/env bash
# Configures an Nginx server so that it Configures Nginx server
apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello School" > /etc/nginx/html/index.html
printf %s "server {
	listen 80;
	listen 54.85.94.172:80 default_server;
	root   /etc/nginx/html;
	index  index.html index.htm;
	X-Served-By: 103698-web-01
	location /redirect_me {
		return 301 http://cuberule.com/;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
