#!/usr/bin/env bash
# Configures an Nginx server so that it Configures Nginx server
apt-get update
apt-get install -y nginx

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello School" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page"> /etc/ww/html/404.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html index.htm;
	add_header X-Served-By $HOSTNAME;
	location /redirect_me {
		return 301 http://smchibwe.tech/;
	}
	
	error_page 404 /404.html;
	location /404 {
	root /etc/nginx/sites-available/defult;
	internal;
}
}" > /etc/nginx/sites-available/default

service nginx restart
