#!/usr/bin/env bash
# Script that configures my NGINX Server to start listening to port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
