#!/usr/bin/env bash
# Script that configures a NGINX Server to start listening on port 80

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
start nginx service
kill "$(pgrep 'nginx' | head -1)"
