#!/usr/bin/env bash
# Configures nginx to nginx user while listening on port 8080

service nginx stop

# Change ownership of Nginx files to nginx user
chown -R nginx:nginx /etc/nginx

# Edit the Nginx configuration file to run as nginx user & listen on port 8080
sed -i 's/user\s*nginx;/user nginx;\n	listen	8080;/g' /etc/nginx/nginx.conf

# Restart Nginx
service nginx start
